version: '3'
services:
  app:
    image: app
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
    command: sh -c "sleep 10"
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - 3306:3306
